#THIS IS THE SCRIPT CREATING SAMPLES OF PARAMETERS FOR THE ESTIMATION
#install.packages("lhs")
library(lhs)
library(plyr)
set.seed(10000)
combinations=100000    
npars=48 #43 sectors + alpha, beta + 3 final columns

Sample<-randomLHS(combinations,npars)      #Latin Hypercube sampling from parameter spaces defined in parenthesis

#take Reissl et al. (2022a)'s parameter spaces 
#for the parameter space see Table D1 pag 44 Reissl et al (2022a)
Sample[,1]<-qunif(Sample[,1],0.02,0.05)     #alpha param space
Sample[,2]<-qunif(Sample[,2],1,52)          #beta param space
Sample[,3]<-qunif(Sample[,3],2,26)          #gamma 1 -> sector 1 (agriculture, forestry and fishing) 
Sample[,4]<-Sample[,3]                       #gamma 1 -> sector 2 (agriculture, forestry and fishing)  
Sample[,5]<-qunif(Sample[,5],2,26)          #gamma 2 -> sector 3 (mining and quarrying) 
Sample[,6]<-qunif(Sample[,6],2,26)          #gamma 3 -> sector 4 (manufacturing)  
Sample[,7]<-Sample[,6]                       #gamma 3 -> sector 5 (manufacturing)  
Sample[,8]<-Sample[,6]                       #gamma 3 -> sector 6 (manufacturing) 
Sample[,9]<-Sample[,6]                       #gamma 3 -> sector 7 (manufacturing) 
Sample[,10]<-Sample[,6]                      #gamma 3 -> sector 8 (manufacturing) 
Sample[,11]<-Sample[,6]                      #gamma 3 -> sector 9 (manufacturing) 
Sample[,12]<-Sample[,6]                      #gamma 3 -> sector 10 (manufacturing)
Sample[,13]<-Sample[,6]                      #gamma 3 -> sector 11 (manufacturing) 
Sample[,14]<-Sample[,6]                      #gamma 3 -> sector 12 (manufacturing) 
Sample[,15]<-Sample[,6]                      #gamma 3 -> sector 13 (manufacturing) 
Sample[,16]<-Sample[,6]                      #gamma 3 -> sector 14 (manufacturing) 
Sample[,17]<-Sample[,6]                      #gamma 3 -> sector 15 (manufacturing) 
Sample[,18]<-Sample[,6]                      #gamma 3 -> sector 16 (manufacturing) 
Sample[,19]<-Sample[,6]                      #gamma 3 -> sector 17 (manufacturing)   
Sample[,20]<-Sample[,6]                      #gamma 3 -> sector 18 (manufacturing) 
Sample[,21]<-Sample[,6]                      #gamma 3 -> sector 19 (manufacturing) 
Sample[,22]<-Sample[,6]                      #gamma 3 -> sector 20 (manufacturing) 
Sample[,23]<-Sample[,6]                      #gamma 3 -> sector 21 (manufacturing) 
Sample[,24]<-Sample[,6]                      #gamma 3 -> sector 22 (manufacturing) 
Sample[,25]<-qunif(Sample[,25],2,26)       #gamma 4 -> sector 23 (electricity generation and water supply) 
Sample[,26]<-Sample[,25]                     #gamma 4 -> sector 24 (electricity generation and water supply) 
Sample[,27]<-Sample[,25]                     #gamma 4 -> sector 25 (electricity generation and water supply) 
Sample[,28]<-qunif(Sample[,28],2,26)        #gamma 5 -> sector 26 (construction) 
Sample[,29]<-qunif(Sample[,29],2,26)        #gamma 6 -> sector 27 (services) 
Sample[,30]<-Sample[,29]                     #gamma 6 -> sector 28 (services) 
Sample[,31]<-Sample[,29]                     #gamma 6 -> sector 29 (services) 
Sample[,32]<-Sample[,29]                     #gamma 6 -> sector 30 (services) 
Sample[,33]<-Sample[,29]                     #gamma 6 -> sector 31 (services) 
Sample[,34]<-Sample[,29]                     #gamma 6 -> sector 32 (services) 
Sample[,35]<-Sample[,29]                     #gamma 6 -> sector 33 (services) 
Sample[,36]<-Sample[,29]                     #gamma 6 -> sector 34 (services) 
Sample[,37]<-Sample[,29]                     #gamma 6 -> sector 35 (services) 
Sample[,38]<-Sample[,29]                     #gamma 6 -> sector 36 (services) 
Sample[,39]<-Sample[,29]                     #gamma 6 -> sector 37 (services) 
Sample[,40]<-Sample[,29]                     #gamma 6 -> sector 38 (services) 
Sample[,41]<-Sample[,29]                     #gamma 6 -> sector 39 (services) 
Sample[,42]<-Sample[,29]                     #gamma 6 -> sector 40 (services) 
Sample[,43]<-Sample[,29]                     #gamma 6 -> sector 41 (services)   
Sample[,44]<-Sample[,29]                     #gamma 6 -> sector 42 (services) 
Sample[,45]<-Sample[,29]                     #gamma 6 -> sector 43 (services) 
Sample[,46]<-qunif(Sample[,46],-3,3)
Sample[,47]<-qunif(Sample[,47],-3,3)
Sample[,48]<-qunif(Sample[,48],-3,3)




Sample[,1]<-round(Sample[,1],digits = 3)
Sample[,2]<-round(Sample[,2],digits = 0)
Sample[,3]<-round(Sample[,3],digits = 0)
Sample[,4]<-round(Sample[,4],digits = 0)
Sample[,5]<-round(Sample[,5],digits = 0)
Sample[,6]<-round(Sample[,6],digits = 0)
Sample[,7]<-round(Sample[,7],digits = 0)
Sample[,8]<-round(Sample[,8],digits = 0)
Sample[,9]<-round(Sample[,9],digits = 0)
Sample[,10]<-round(Sample[,10],digits = 0)
Sample[,11]<-round(Sample[,11],digits = 0)
Sample[,12]<-round(Sample[,12],digits = 0)
Sample[,13]<-round(Sample[,13],digits = 0)
Sample[,14]<-round(Sample[,14],digits = 0)
Sample[,15]<-round(Sample[,15],digits = 0)
Sample[,16]<-round(Sample[,16],digits = 0)
Sample[,17]<-round(Sample[,17],digits = 0)
Sample[,18]<-round(Sample[,18],digits = 0)
Sample[,19]<-round(Sample[,19],digits = 0)
Sample[,20]<-round(Sample[,20],digits = 0)
Sample[,21]<-round(Sample[,21],digits = 0)
Sample[,22]<-round(Sample[,22],digits = 0)
Sample[,23]<-round(Sample[,23],digits = 0)
Sample[,24]<-round(Sample[,24],digits = 0)
Sample[,25]<-round(Sample[,25],digits = 0)
Sample[,26]<-round(Sample[,26],digits = 0)
Sample[,27]<-round(Sample[,27],digits = 0)
Sample[,28]<-round(Sample[,28],digits = 0)
Sample[,29]<-round(Sample[,29],digits = 0)
Sample[,30]<-round(Sample[,30],digits = 0)
Sample[,31]<-round(Sample[,31],digits = 0)
Sample[,32]<-round(Sample[,32],digits = 0)
Sample[,33]<-round(Sample[,33],digits = 0)
Sample[,34]<-round(Sample[,34],digits = 0)
Sample[,35]<-round(Sample[,35],digits = 0)
Sample[,36]<-round(Sample[,36],digits = 0)
Sample[,37]<-round(Sample[,37],digits = 0)
Sample[,38]<-round(Sample[,38],digits = 0)
Sample[,39]<-round(Sample[,39],digits = 0)
Sample[,40]<-round(Sample[,40],digits = 0)
Sample[,41]<-round(Sample[,41],digits = 0)
Sample[,42]<-round(Sample[,42],digits = 0)
Sample[,43]<-round(Sample[,43],digits = 0)
Sample[,44]<-round(Sample[,44],digits = 0)
Sample[,45]<-round(Sample[,45],digits = 0)
Sample[,46]<-round(Sample[,46],digits = 1)
Sample[,47]<-round(Sample[,47],digits = 1)
Sample[,48]<-round(Sample[,48],digits = 1)

write.csv(Sample, file = "resources/Sample_FullParamSpace_REV1_DiffCons.csv",row.names=FALSE)


